hostutils: phoenixd: break from loop after connection lost on port
phoenix-rtos/phoenixd pull request #23
Opened 2021-06-22 12:08 UTC by niewim19

JIRA: PD-29

phoenixd closes itself after connection lost

## Description
break from loop in message dispatch in phoenixd

## Motivation and Context
This change allows for further automation of development process. User may create a bash script that rapidly runs the phoenixd, thus user does not have to "aim" with phoenixd when plo starts.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## How Has This Been Tested?

- [ ] Already covered by automatic testing.
- [ ] New test added: (add PR link here).
- [x] Tested by hand on: imxrt1066.

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing linter checks and tests passed.
- [x] My changes generate no new compilation warnings for any of the targets.

## Special treatment

- [ ] This PR needs additional PRs to work (list the PRs, preferably in merge-order).
- [ ] I will merge this PR by myself when appropriate.

2021-06-22 12:17 UTC, HBuczynski requested changes
I suppose that you have tested it on `imxrt1064` instead of `imxrt1066`, please update PR message ;)
Please change commit message. It should be written in the following order:
`hostutils/phoenixd:` instead of `hostutils: phoenixd:`

2021-06-22 12:20 UTC, niewim19 commented
Thanks, my mistake with `imxrt1066`. Changed also the commit message

2021-06-22 12:22 UTC, HBuczynski submitted a review, later dismissed

2021-06-22 12:54 UTC, nalajcie commented
@jsarzy - please verify if it won't break testing using test runner

@niewim19: no need for `hostutils` prefix in commit message - You're commiting to `phoenix-rtos-hostutils` repo :)

2021-06-22 13:31 UTC, jsarzy commented
@nalajcie - it breaks imxrt106x part. As the imxrt106x runner is not launched yet it's not a problem. I'm going to prepare fix today.

2021-06-23 08:32 UTC, niewim19 commented
@nalajcie Yes, you are right. `hostutils` was removed from commit message.
@jsarzy If the fix is ready please approve PR. This change, aside from future phoenixd refactor really speeds up development
@Maxez Please check if this change is not crucial for ia32 on qemu, because (as we spoke) phoenixd is in some cases used on ia32 and there are even comments about it in the code.

2021-06-23 13:18 UTC, jsarzy commented
I didn't have time to prepare a fix, but is not problem right now, so for me it can be merged.

2021-06-23 13:19 UTC, jsarzy approved these changes

2021-06-24 06:54 UTC, merged